_target_: src.models.edge_update_model.EdgeUpdateNetWrapper

lr: 0.001
weight_decay: 0
normalize_labels: True
mean: -1.525913953781128
std: 2.279365062713623
hidden_channels: 64
num_interactions: 3
cutoff: 6
